<template>
  <view class="index">
    <mt-background></mt-background>
    <mt-navbar title="工作台" :config="navbarConfig"></mt-navbar>
    <mt-tabs type="scroll" :tabData="scrollTabData"></mt-tabs>

    <view class="index_module">
      <mt-grid name="title" :data="homeModule" :config="gridConfig"></mt-grid>
    </view>
  </view>
</template>

<script>
export default {
  data() {
    return {
      gridConfig: {
        iconWidth: '50px',
        iconHeight: '58px',
        iconPadding: '0 0 14rpx 0',
      },
      navbarConfig: {
        back: false,
      },
      scrollTabData: [{
        id: 0,
        title: "生产监控"
      }, {
        id: 1,
        title: "装置负荷"
      }, {
        id: 2,
        title: "库存分析"
      }, {
        id: 3,
        title: "发货分析"
      }, {
        id: 4,
        title: "原材料"
      }, {
        id: 5,
        title: "生产计划"
      }],
      titleData: [{
        menuName: "测试模块2",
        children: [{
          icon: "https://m.firstui.cn/static/images/common/icon_tabbar_3x.png",
          menuName: "测试模块",
          url: ""
        }, {
          icon: "https://m.firstui.cn/static/images/common/icon_tabbar_3x.png",
          menuName: "diy模块",
          type: "diy",
          url: ""
        }, {
          icon: "https://m.firstui.cn/static/images/common/icon_tabbar_3x.png",
          menuName: "diy模块",
          type: "diy",
          url: ""
        }, {
          icon: "https://m.firstui.cn/static/images/common/icon_tabbar_3x.png",
          menuName: "diy模块",
          type: "diy",
          url: ""
        }],
        url: ""
      }],

      homeModule: [{
        menuName: "常用应用",
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1445",
          "menuName": "考勤打卡",
          "parentName": null,
          "parentId": 1443,
          "sort": 2,
          "path": "/pages/checkOn/checkOn",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0817/99f6d654e80244e1ad46e965c8c764cc.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1446",
          "menuName": "事件上报",
          "parentName": null,
          "parentId": 1443,
          "sort": 3,
          "path": "/pages/eventExtend/event_report?moduleType=eventReprot&firstCode=-1",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/d73ff9c3eb32411eb31929a392706863.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1450",
          "menuName": "添加",
          "parentName": null,
          "parentId": 1443,
          "sort": 7,
          "path": "/pages/workDesk/editWorkDesk?moduleType=more",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0817/d3ad308b92754e51adbce9ae7186a87d.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1370",
        "menuName": "事件协同",
        "parentName": null,
        "parentId": 1000002,
        "sort": 2,
        "path": "#",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1374",
          "menuName": "事件上报",
          "parentName": null,
          "parentId": 1370,
          "sort": 1,
          "path": "/pages/eventExtend/event_report?moduleType=eventReprot&firstCode=-1",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/d73ff9c3eb32411eb31929a392706863.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1648",
          "menuName": "事件审核",
          "parentName": null,
          "parentId": 1370,
          "sort": 2,
          "path": "/pages/mainListSimple/mainList?moduleType=examine",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/sjsh.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1649",
          "menuName": "待办事件",
          "parentName": null,
          "parentId": 1370,
          "sort": 3,
          "path": "/pages/mainListEvents/mainList?moduleType=todo",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/2b4465d29e57430e8522bf37cddb72c6.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1375",
          "menuName": "我的事件",
          "parentName": null,
          "parentId": 1370,
          "sort": 4,
          "path": "/pages/mainListEvents/mainList?moduleType=myEvents",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/4c657dfe0fc542bf8378578af622bfe4.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1440",
          "menuName": "草稿箱",
          "parentName": null,
          "parentId": 1370,
          "sort": 5,
          "path": "/pages/mainListDraft/mainList?moduleType=draftbox",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0805/4d5593c66c1640e6b8f17128de6de671.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1698",
          "menuName": "通知公告",
          "parentName": null,
          "parentId": 1370,
          "sort": 6,
          "path": "/pages/mainListNotice/mainList?moduleType=notice",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/tongZhiGongGao.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1709",
          "menuName": "经办事件",
          "parentName": null,
          "parentId": 1370,
          "sort": 7,
          "path": "/pages/mainListEvents/mainList?moduleType=done",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/jingban.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1639",
        "menuName": "多网融合",
        "parentName": null,
        "parentId": 1000002,
        "sort": 4,
        "path": "#",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1640",
          "menuName": "调诉一体化",
          "parentName": null,
          "parentId": 1639,
          "sort": 1,
          "path": "/pages/eventExtend/event_report?firstCode=0",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/yqfk/ryxx.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1644",
          "menuName": "疫情上报",
          "parentName": null,
          "parentId": 1639,
          "sort": 5,
          "path": "/pages/eventExtend/event_report?firstCode=1",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/yqfk/yqsb.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1645",
          "menuName": "防疫日志",
          "parentName": null,
          "parentId": 1639,
          "sort": 6,
          "path": "/pages/mainListDaily/mainList?moduleType=preventLog",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/yqfk/fyrz.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1228",
        "menuName": "信息采集",
        "parentName": null,
        "parentId": 1000002,
        "sort": 5,
        "path": "datacollection",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1230",
          "menuName": "建筑采集",
          "parentName": null,
          "parentId": 1228,
          "sort": 1,
          "path": "/pages/mainListInfrastructure/mainList?moduleType=building",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/3d99e7a9c39648e6b93b3978eabd0238.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1231",
          "menuName": "房屋登记",
          "parentName": null,
          "parentId": 1228,
          "sort": 2,
          "path": "/pages/mainListInfrastructure/mainList?moduleType=house",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/54c803cfbde14610a9a9e0c46503708b.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1233",
          "menuName": "户籍人口",
          "parentName": null,
          "parentId": 1228,
          "sort": 4,
          "path": "/pages/mainListPopulation/mainList?moduleType=registered",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/91ab44dc2e904fda92e477cd8d461ee6.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1234",
          "menuName": "流动人口",
          "parentName": null,
          "parentId": 1228,
          "sort": 5,
          "path": "/pages/mainListPopulation/mainList?moduleType=flow",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/e8ac0f5a300c42eb895da6686e811a3f.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1235",
          "menuName": "境外人口",
          "parentName": null,
          "parentId": 1228,
          "sort": 6,
          "path": "/pages/mainListPopulation/mainList?moduleType=abroad",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/ffdf2f7056d94fad8b9d41223d2d47b2.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1237",
          "menuName": "独居老人",
          "parentName": null,
          "parentId": 1228,
          "sort": 7,
          "path": "/pages/mainListSpecial/mainList?moduleType=livingAlone",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/d193c66fd6144eabb5e7af98f14d3002.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1238",
          "menuName": "残疾人员",
          "parentName": null,
          "parentId": 1228,
          "sort": 8,
          "path": "/pages/mainListSpecial/mainList?moduleType=disabled",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/82267a63db924bb9997d8f337d0efb27.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1239",
          "menuName": "失业人员",
          "parentName": null,
          "parentId": 1228,
          "sort": 9,
          "path": "/pages/mainListSpecial/mainList?moduleType=unemployed",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/4e6c5445de7b4cd5aa8c3ca876973cd2.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1240",
          "menuName": "留守儿童",
          "parentName": null,
          "parentId": 1228,
          "sort": 10,
          "path": "/pages/mainListSpecial/mainList?moduleType=leftBehind",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/3716ab842c084352a1736b2c1459d2db.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1717",
          "menuName": "信访人员",
          "parentName": null,
          "parentId": 1228,
          "sort": 10,
          "path": "/pages/mainListSpecial/mainList?moduleType=letters",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/yqfk/xin_fang.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1646",
          "menuName": "社会组织",
          "parentName": null,
          "parentId": 1228,
          "sort": 11,
          "path": "/pages/mainListSocial/mainList?moduleType=socialOrgan",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/shzz.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1696",
          "menuName": "非公有制经济组织",
          "parentName": null,
          "parentId": 1228,
          "sort": 12,
          "path": "/pages/mainListSocial/mainList?moduleType=nonPublic",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/feiGongYouZhi.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1229",
        "menuName": "重点监管",
        "parentName": null,
        "parentId": 1000002,
        "sort": 6,
        "path": "#",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1241",
          "menuName": "社区矫正人员",
          "parentName": null,
          "parentId": 1229,
          "sort": 1,
          "path": "/pages/mainListSpecial/mainList?moduleType=correct",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/3c61c14339c442b3b8247c73df468bb7.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1242",
          "menuName": "吸毒人员",
          "parentName": null,
          "parentId": 1229,
          "sort": 2,
          "path": "/pages/mainListSpecial/mainList?moduleType=drug",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/3ad560b123e14b84b3f17081b7cd7f19.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1243",
          "menuName": "肇事肇祸等严重精神障碍患者",
          "parentName": null,
          "parentId": 1229,
          "sort": 3,
          "path": "/pages/mainListSpecial/mainList?moduleType=psychopath",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/48809ba57e5e49e2bb38e8dce5459455.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1245",
          "menuName": "刑满释放人员",
          "parentName": null,
          "parentId": 1229,
          "sort": 5,
          "path": "/pages/mainListSpecial/mainList?moduleType=release",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0616/f0695cd1666d4e5abc75f109e3bcc5fc.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1659",
        "menuName": "统计分析",
        "parentName": null,
        "parentId": 1000002,
        "sort": 7,
        "path": "#",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1660",
          "menuName": "个人排名统计",
          "parentName": null,
          "parentId": 1659,
          "sort": 1,
          "path": "/pages/census/personal",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/grpm.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1661",
          "menuName": "巡查时长统计",
          "parentName": null,
          "parentId": 1659,
          "sort": 2,
          "path": "/pages/census/visitedDur",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/xcsc.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1662",
          "menuName": "事件数量统计",
          "parentName": null,
          "parentId": 1659,
          "sort": 3,
          "path": "/pages/census/eventNum",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/sjtj.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1663",
          "menuName": "事件办结统计",
          "parentName": null,
          "parentId": 1659,
          "sort": 4,
          "path": "/pages/census/eventDone",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/sjbj.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1664",
          "menuName": "网格概览统计",
          "parentName": null,
          "parentId": 1659,
          "sort": 5,
          "path": "/pages/census/gridChance",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/wggl.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1652",
        "menuName": "网格日常",
        "parentName": null,
        "parentId": 1000002,
        "sort": 8,
        "path": "#",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1653",
          "menuName": "考勤打卡",
          "parentName": null,
          "parentId": 1652,
          "sort": 1,
          "path": "/pages/checkOn/checkOn",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0817/99f6d654e80244e1ad46e965c8c764cc.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1654",
          "menuName": "网格日志",
          "parentName": null,
          "parentId": 1652,
          "sort": 2,
          "path": "/pages/mainListDaily/mainList?moduleType=gridLog",
          "component": null,
          "icon": "http://wx.gisocn.com:19100/server-file-priview/upload/2021/appSource/menu/0817/7e47610353c74e7ca48dcb95687a8710.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }, {
        "id": "1656",
        "menuName": "网格学苑",
        "parentName": null,
        "parentId": 1000002,
        "sort": 9,
        "path": "#",
        "component": null,
        "icon": "#",
        "status": 0,
        "children": [{
          "id": "1657",
          "menuName": "学习园地",
          "parentName": null,
          "parentId": 1656,
          "sort": 1,
          "path": "/pages/gridStudy/studyPlace",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/xxyd.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }, {
          "id": "1658",
          "menuName": "在线考试",
          "parentName": null,
          "parentId": 1656,
          "sort": 2,
          "path": "/pages/onlineTest/list",
          "component": null,
          "icon": "http://120.220.3.184:18080/file/upload/static/images/other/zxks.png",
          "status": 0,
          "children": [],
          "isFrame": 1,
          "menuType": "C",
          "visible": "0",
          "exceedUrl": null
        }],
        "isFrame": 1,
        "menuType": "M",
        "visible": "0",
        "exceedUrl": null
      }]
    }
  },
  onShow() {
    this.getMenu()
  },
  methods: {
    getMenu() {
      return new Promise((resolve, reject) => {
        this.$mt.get({
          url: 'getMenuNew',
          type: 'login'
        }, {
          parentId: "1000002",
        }).then(res => {
          if (res.code == 0) {
            if (!res.dataList || res.dataList.length < 1) {
              uni.showToast({
                title: "暂未配置菜单哦",
              })
              return
            }
            res.dataList = res.dataList.forEach(v => {

            })
            resolve(res.dataList)
          }
        })
            .catch((err) => {
              reject(err)
            })
      })
    },

    navbarEvent() {
      console.log("触发自定义方法")
    }
  }
}
</script>

<style lang="scss" scoped>
.index {
  &_module {
    padding: 20rpx;
  }
}
</style>
